### ISSUE TITLE
Kickstart

### ISSUE THREAD

**Issue by SimenB** [schibsted/eslint-config-spt#21]
Trying to somewhat kickstart this convo.

- Do we want to just use Airbnb's config, or do we want to get a diff from our current one to migrate?
  - Then we should try to script it, [eslint-index](https://www.npmjs.com/package/eslint-index) looks interesting
  - Might be better to just start fresh, I don't know who at SPT came up with the original rules, how much consensus was there?
- Should we extend Airbnb, or should we copy over rules?
    - If we copy over, do we want to keep all the plugins (import, a11y etc)?
- I'd like for a base config to not include react (or other frameworks), those can be added as extras (like it is now, makes a lot of sense if we later have e.g. Angular specific configs)
- Separate config for node? While async/await has landed behind a flag, stuff like modules is still someway off. Keeping web/server separate might be a good idea
  - Then we could use e.g. the node plugin

We should try to get some actionable points out of this, so we can get some progress.

**Comment by ivarconr** [comment]
I vote for us to have our own base with our rules. Can of course be a copy of AirBnB base, but we should have the possibility to go our own way

**Comment by alexewerlof** [comment]
> Do we want to just use Airbnb's config, or do we want to get a diff from our current one to migrate?
> Should we extend Airbnb, or should we copy over rules?

Certainly forking AirBnB or staying as close to it as possible is the way to go since internally AirBnB is the most used base.

> eslint-index looks interesting

It does. 👍 Maybe first set our rules and then for the next milestone we can spend some resources on that?

> I'd like for a base config to not include react (or other frameworks), those can be added as extras (like it is now, makes a lot of sense if we later have e.g. Angular specific configs)

👍

**Comment by alexewerlof** [comment]
Think we're done with the kickstart 👍 
Great job everyone involved in this. Let's continue the discussion if the channel or issues if needed.
