### ISSUE TITLE
Retire the project?

### ISSUE THREAD

**Issue by nosilleg** [schibsted/eslint-config-spt#215]
I haven't made any significant updates to this project in over a year, and I'm not sure that this has been noticed.

Unless there's feedback within the next two weeks I'll retire the project and set it as unmaintained.

**Comment by alexewerlof** [comment]
Hi Jason,
I talked to @gustavkj who is experienced with ESLint and Dependobot and works at a team which gives a very good chance for this repo to be reused. He's now onboarded and has access to improve the repo.
It was a great ride. :) Hope our path will cross again.
