### ISSUE TITLE
Remove package.json from the root

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#27]
I can't see any reason it's needed. Shall we remove it to reduce confusion?

**Comment by SimenB** [comment]
it's used by the build

**Comment by alexewerlof** [comment]
I can't find the build script. Travis doesn't use it either. Am I missing something?

**Comment by SimenB** [comment]
Travis does `npm install` and `npm test` by default. There are some `postinstall` in root tying it all together.
Might be a good idea to add [Lerna](https://github.com/lerna/lerna)

**Comment by sveisvei** [comment]
As well nice place to run `npm run` in root and get the gist of whats there.

**Comment by alexewerlof** [comment]
Re: discussion on #33 closing this.
