### ISSUE TITLE
Shouldn't the xxx-react package have a peer dependency on -schibsted?

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#28]
https://github.com/schibsted/eslint-config-schibsted/blob/master/packages/eslint-config-schibsted-react/package.json#L15

**Comment by SimenB** [comment]
They are independent, but of course react config doesn't make sense without the base one. So I'm +0 on such a change :smile:

**Comment by alexewerlof** [comment]
If it's independent, well done. 👍 
It's better not to impose the core configs.
Closing this one then.
