### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#32]
it can be a bunch of different files demonstrating different edge cases and run them through different eslint configs.

**Comment by SimenB** [comment]
I'm unsure what value that provides.
I would like to run through `eslint-find-rules`, but other than that I don't think tests makes sense.

We should find a way to validate the config, though (just that it's valid, not ran over some code)

**Comment by ivarconr** [comment]
Could have sone examples, but test should only validate that the config works as expected.

**Comment by alexewerlof** [comment]
I get your point. Google also does the same: https://github.com/google/eslint-config-google/tree/master/test just runs the config files through tests.

* But looking at the big picture, if someone makes a change, it's hard to see if it's breaking any of the conventions that we have already established (like different options for `'use strict'`). This is the equivalent to having tests in a code repo: if someone accidentally/willingly makes some changes to the expected behaviour of the code, they have to change the tests to pass too. With test snippets, it's easier to quickly review a PR because you can see how it's affecting those tests in action.
* If we don't have such tests, we have to run every PR through our code base (which already may override some rules) and it takes more time to review a PR properly. If we have small code snippets that we run through various configs, the only way that a breaking change can be introduced, is if the test (snippets) are also updated.
* Besides, some of the current configs that we are shipping are not tested at all (only `index.js` and `env-node.js` are addressed.

The downside of the approach I'm proposing is that we needs to take the time to write those snippets.

**Comment by SimenB** [comment]
Any change that will add an error (or warning) in consumer code is a breaking change, even if it's just one error in a 50k LOC project.
Loosening of rules are patches, and features should be minor (such as enabling syntax like object rest).

I don't think we need tests to validate that, it'd be pretty obvious from the change itself.

But we should validate that config is valid somehow, also config not used directly in this project

**Comment by alexewerlof** [comment]
> we should validate that config is valid somehow 

Convinced.

So the process will be like this:

* We publish a valid config
* It's up to users (including our other "work projects") to try it and report if it's breaking something. Then they decide if they want to upgrade the version or stay with whatever minor/patch they are using.
* We discuss/fix the requested issue and maybe release a new minor/path.

**Comment by SimenB** [comment]
Yeah, sounds about right 😄
