### ISSUE TITLE
Use Travis build matrix for running tests

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#33]
Let travis run tests on every push.

**Comment by SimenB** [comment]
It does this today. We don't have tests beyond linting the code, but travis is set up

**Comment by alexewerlof** [comment]
Yes they currently do. But I am experimenting with Travis build matrix to see if we can remove the package.json in the root (#27).

**Comment by alexewerlof** [comment]
the solution is on https://github.com/schibsted/eslint-config-schibsted/tree/travis-build-tests
it'll work when #36 is merged.

**Comment by SimenB** [comment]
I still think we should keep the package.json in root. I want to be able to clone a repo, cd into it, and run `npm it`. Whether or not Travis does the same is w/e to me, but I don't want to check `.travis.yml` to understand how to contribute.

**Comment by alexewerlof** [comment]
>  I want to be able to clone a repo, cd into it, and run npm it.
Yeah that's a convenience Travis doesn't provide. Closing
