### ISSUE TITLE
Indent = 2

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#34]
The biggest difference between `-schibsted` and `-airbnb` is the indentation.
We [use 2](https://github.com/schibsted/eslint-config-schibsted/blob/master/packages/eslint-config-schibsted/index.js#L78) they [use 2](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L79).

This is a huge stopper for our colleagues who want to move from `-airbnb` to `-schibsted` because this means they practically have to touch most lines of their source code to be compatible with `-schibsted`.

I personally have nothing against *4* and indeed used that in all my previous jobs, but *2* [is all the rage](https://seravo.fi/2013/javascript-the-winning-style) these days. Crockford [recommends 4](http://javascript.crockford.com/code.html), Node [recommends 2](https://github.com/felixge/node-style-guide#2-spaces-for-indentation) but good ol' jQuery goes with [tabs that are 4 characters](https://contribute.jquery.org/style-guide/js/).

Sure when it comes to preferences, choices are as diverse as JavaScript community itself and one can always override the default rules but it would be sweet if we settle for a default that takes minimum effort to migrate the bunch of `-airbnb` based code bases to `-schibsted` as effortlessly as possible.

2 = 👍 4 = 👎. Which 🗳 ?

**Comment by SimenB** [comment]
I personally prefer 2, but Finn codebases are all with 4, so if the default is changed here, we'll probably overwrite it.

I vote for 2 as default :smile:

**Comment by alexewerlof** [comment]
Let's keep this open till next week where more people from #frontend have a chance to mention their votes. 👍

**Comment by trygve-lie** [comment]
To be honest, I find discussions on number of spaces and tabs vs spaces counterproductive. Its mostly about personal preference and has no to little effect on your code base. My opinion is; pick one and stick with one (don't mix) and its fine if its different between projects but developers must respect whats being used in each project.

Though; that is hard to put into a eslint rule.

**Comment by SimenB** [comment]
An .editorconfig file makes most modern editors (with perhaps a plugin insatlled) respect indentation. So it's relatively simple to make it so you don't have to tweak editor settings on a project by project basis

**Comment by trygve-lie** [comment]
@SimenB exactly my point.

**Comment by alexewerlof** [comment]
@trygve-lie I don't think there's any experienced programmer who would disagree with what you just said.

> To be honest, I find discussions on number of spaces and tabs vs spaces counterproductive.

We too. That's why we aim to settle for good defaults so people don't *have to override them inconsistently* for every project. Linting rules are arguably the most opinionated piece of work so it's good to reach some consensus. That being said, voting is not obligatory. 🗳

**Comment by nosilleg** [comment]
Addressed in https://github.com/schibsted/eslint-config-schibsted/pull/74 by setting to 2 spaces.

**Comment by nosilleg** [comment]
Closing as fixed in version 6.
