### ISSUE TITLE
Move the two package dirs to the root

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#39]
While working on the repo I had to constantly cd to the two nested dirs. It's a bit unnecessary. I propose we move them into the root so:

```
./
  |__ packages
      |__ eslint-config-schibsted
      |__ eslint-config-schibsted-react    
```

will look like:

```
./
  |__ eslint-config-schibsted
  |__ eslint-config-schibsted-react    
```

**Comment by SimenB** [comment]
It's a standard for monorepos to have that structure (see babel, jest, react etc). 
I would rather add lerna to manage it

**Comment by alexewerlof** [comment]
> It's a standard for monorepos to have that structure (see babel, jest, react etc).

Convinced. Closing it. Can you open an issue for Lerna mentioning the cons and pros? 👍
