### ISSUE TITLE
Add a CONTRIBUTING.md page

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#40]
# What?

`./CONTRIBUTING.md` as discussed in:
* https://github.com/blog/1184-contributing-guidelines
* https://help.github.com/articles/setting-guidelines-for-repository-contributors/

# Why?

So that we have a clear path to anyone who wants to discuss rules or submit a PR with minimum confusion and higher efficiency.

# How?

This is an initial text I had in mind. Any addition/edition? Discuss on this issue.

````
## Discussion

Since this linting config is used in code bases affect various internal and external users for code that are shipped to several million people, it's important to seek consensus before changing the rules.

Opening an issue and explaining your case would be the best way to start the discussion.
If you work at Schibsted, join `#eslint-config-schibst` Slack channel.

## Publishing

```bash
# Make sure to only make do this in the package that has changed
# Update CHANGELOG
$ npm version <patch | minor | major>
$ git push --tags origin master
$ npm publish
```
````

*Then review the README.md file and add refs*

**Comment by SimenB** [comment]
SGTM. Typo in slack channel, other than that the text is fine

**Comment by alexewerlof** [comment]
Thanks. Fixed typo 👍

**Comment by ivarconr** [comment]
Should we also include a small paragraph on how to write commit messages? 

At least commits changing rules should be explicit and state why the rule is changed and link to the relevant issue where the discussion took place. We should also avoid changing a lot of unrelated rules in one commit.

**Comment by alexewerlof** [comment]
@ivarconr good idea. Just give me a text and I can add that 👍
