### ISSUE TITLE
Use package.json for the list of authors

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#41]
# Why?

A way to credit people involved in the code.
The problem is that we duplicated this info in `./AUTHORS.md` and `package.json`. So adding new people required touching two files. It might be unnecessary altogether since Github automatically generates [this list](https://github.com/schibsted/eslint-config-schibsted/graphs/contributors) for us anyway.

But one reason for having it would be to list individual contributors to each sub-package separatly (IMHO: too much bookkeeping, but we gotta give credit to those who are involved). For example if someone has been contributing to the `eslint-config-schibsted-react` their name can be in `eslint-config-schibsted-react/package.json:contributors` array.

# What?
[Here is the format](https://docs.npmjs.com/files/package.json#people-fields-author-contributors)
[./AUTHORS.md]()

And here is [a discussion](https://github.com/expressjs/express/issues/2852) express.js team had on the issue and concluded not to have AUTHORS.md

# How?

* Replace the `"author"` field in the `packages/**/package.json` with an array of `"contributors"`.
* Remove `"author"` from `./package.json`
* Remove `./AUTHORS.md`
* Optionally use single-line format for `"contributors"` field in package.json
* Add whatever process is decided here to the `./CONTRIBUTING.md` file that comes out of #40

**Comment by ivarconr** [comment]
> npm will default some values based on package contents.
> 
> "contributors": [...]
> 
> If there is an AUTHORS file in the root of your package, npm will treat each line as a Name <email> (url) format, where email and url are optional. Lines which start with a # or are blank, will be ignored.
(https://docs.npmjs.com/files/package.json#default-values)

Why not have a AUTHORS file automatically generated from the git history? I have sometimes used this script for doing exacly that:

`git log --format='%aN <%aE>' | sort -f | uniq`

**Comment by alexewerlof** [comment]
While researching Standard (#47) I found they are using something similar (but [a bit less elegant](https://github.com/feross/standard/blob/master/bin/update-authors.sh) than what @ivarconr posted 👆 )

**Comment by nosilleg** [comment]
Closing this as it seems you two agreed that we should keep Author.md, and the express discussion says that they use .mailmap instead, which isn't being considered here.
