### ISSUE TITLE
Use Lerna

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#44]
I did a little feasibility test to see if we can use [Lerna](https://lernajs.io/) for handling our two packages.

Turns out [Lerna doesn't support Yarn](https://github.com/lerna/lerna/issues/371) yet. Interestingly Jest from Facebook (the company who made Yarn on the first place [is still using Lerna](https://github.com/facebook/jest/blob/master/lerna.json) *v2.0.0-beta.31* despite using [yarn](https://github.com/facebook/jest/blob/master/yarn.lock)).

Anyway, [there are a bunch of yarn issues](https://github.com/lerna/lerna/issues?utf8=%E2%9C%93&q=yarn) on Lerna that one has to investigate.

My two cents:

* Use the `package.json` in the root for now until we have enough packages that justifies bringing another dependency into the project
* Wait and see if Lerna supports Yarn fully or [Yarn will swallow Lerna](https://github.com/yarnpkg/yarn/issues/946#issuecomment-264597575). Either way, it seems to early to decide.

**Comment by SimenB** [comment]
We should wait to see what happens in lerna/lerna#371, there's probably some news not too far out

**Comment by nosilleg** [comment]
For reference https://github.com/finn-no/eslint-config-finn/commit/1ca0340bb9110a6b4248ce86ed255c06032a7d45
