### ISSUE TITLE
Look into Roc config

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#48]
https://github.com/rocjs/roc-package-web-app-react/blob/master/extensions/roc-package-web-app-react/package.json#L59

**Comment by SimenB** [comment]
What to do here? It uses airbnb

**Comment by alexewerlof** [comment]
I meant their overrides: 
* https://github.com/rocjs/roc-package-web-app-react/blob/master/extensions/roc-package-web-app-react/.eslintrc
* https://github.com/rocjs/roc-package-web-app-react/blob/master/extensions/roc-package-web-app-react-dev/.eslintrc

**Comment by dlmr** [comment]
Does this issue refer to _Roc_ or _Rocket_? Both projects use AirBnB but with different overrides.

**Comment by alexewerlof** [comment]
Good point @dlmr 👍  Roc. Fixed the title.

**Comment by alexewerlof** [comment]
Referencing Roc issue here for the record: https://github.schibsted.io/vg/feather/pull/120

**Comment by andreasrs** [comment]
@userpixel A quick clarification: The link above uses Roc (web-app-react), but uses its own airbnb-based linting config.

**Comment by nosilleg** [comment]
Closing this as consumers of eslint-config-schibsted can extend the config the same way they are overriding AirBnB.  If there are some config options where we think we should be doing something different from AirBnB, then those should be brought up in their own ticket.
