### ISSUE TITLE
Look into xo

### ISSUE THREAD

**Issue by dlmr** [schibsted/eslint-config-spt#53]
[xo](https://github.com/sindresorhus/xo) is a wrapper around ESLint by Sindre Sorhus that aims for the following.

> Opinionated but configurable ESLint wrapper with lots of goodies included. Enforces strict and readable code. Never discuss code style on a pull request again! No decision-making. No .eslintrc or .jshintrc to manage. It just works!

Might be interesting to look at it for inspiration on how to make the configuration easy to work with in different projects.

**Comment by alexewerlof** [comment]
Thanks @dlmr 
Have you looked into StandardJS #47? I'm wondering what are the differences because they sound very similar. Haven't worked with any of them TBH.

**Comment by dlmr** [comment]
I have look at it and followed along with some of the discussions surrounding it, coding standards is something that many have an opinion about, but I have never used either of them.

[This is what Sindre writes himself about the two projects.](https://github.com/sindresorhus/xo#why-not-standard)

**Comment by userpixel** [comment]
Oh, didn't notice it was Made in Norway 🇳🇴 
Yet another reason to take it seriously. I'll give it a try for sure as part of this research. Thanks for bringing it into our attention. 👍

**Comment by alexewerlof** [comment]
Update: Messaging team who uses StandardJS #47 didn't look into XO because they were happy with what StandardJS did at the time.

**Comment by alexewerlof** [comment]
Its eslint config can be found at https://github.com/sindresorhus/eslint-config-xo

**Comment by nosilleg** [comment]
Addressed in https://github.com/schibsted/eslint-config-schibsted/pull/74 by going with AirBnB. Suggest closing this as wontfix.

**Comment by nosilleg** [comment]
As per last message, closing this as we've gone with AirBnB as the base.
