### ISSUE TITLE
Add support for react accessibility

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#58]
These are the rules from airbnb.
We need some react dev to go through them and add the ones relevant (or add all). Airbnb uses MIT but after listening to [this episode of JSJ](https://devchat.tv/js-jabber/238-jsj-intellectual-property-and-software-forensics-with-bob-zeidman) it's better to be on the safe side and not copy/paste them.
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react-a11y.js

*Implementation needs to go to the `next` branch.*

A funny side note: I encountered [this error](https://github.com/airbnb/javascript/issues/1212) and it turns out airbnb doesn't support the latest `eslint-plugin-jsx-a11y`(v3.0.2). Not saying airbnb is 💩  but it's a previous of what's coming for us as maintainers if we have too many dependencies. Needless to say, whoever gets the honour of doing this task will add the config for the latest `eslint-plugin-jsx-a11y` pls :)

**Comment by alexewerlof** [comment]
Since it is yet another dependency, maybe we need a new package for that?

I'm thinking a separate package for configurations that depend on [import](https://www.npmjs.com/package/eslint-plugin-import) as well.

**Comment by SimenB** [comment]
The react package can include this by default, IMO.

**Comment by nosilleg** [comment]
Addressed in https://github.com/schibsted/eslint-config-schibsted/pull/74 with the React package extending react a11y via AirBnB.

**Comment by nosilleg** [comment]
Closing as fixed in version 6.
