### ISSUE TITLE
Remove map(require.resolve)

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#62]
Many times when we extend a config, we are using this pattern:

````
    'extends': [
        './env-es6.js',
        './env-es6-modules-false.js',
        './env-node-false.js'
    ].map(require.resolve),
````

([example](https://github.com/schibsted/eslint-config-schibsted/blob/master/packages/eslint-config-schibsted/index.js#L4)).

This is no more needed now that we directly reference the config files as a result of #45. The `map(require.resolve)` pattern was needed for linking but we don't use that solution anymore.

**Comment by nosilleg** [comment]
Closing this as version 6 has removed `.map(require.resolve)` where it's not needed and kept it where it is needed.
