### ISSUE TITLE
Remove deprecated rules

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#64]
According to [eslint docs](http://eslint.org/docs/rules/#deprecated) the following rules are deprecated.
Check if they are set somewhere.

 - no-native-reassign
 - no-negated-in-lhs
 - no-spaced-func
 - prefer-reflect

Plus [these rules are gone](http://eslint.org/docs/rules/#removed)

**Comment by nosilleg** [comment]
Addressed in https://github.com/schibsted/eslint-config-schibsted/pull/74

**Comment by nosilleg** [comment]
Closing as resolved in version 6.
