### ISSUE TITLE
Use eslint-find-rules to make sure we have good rule coverage

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#65]
[eslint-find-rules](https://www.npmjs.com/package/eslint-find-rules):

> Use this for your own ESLint shareable configuration to list current configured rules, all-available rules, unused rules, and plugin rules.

From [this discussion](https://github.com/schibsted/eslint-config-schibsted/issues/60#issuecomment-270854292)

**Comment by nosilleg** [comment]
Closing this as per #60
