### ISSUE TITLE
Tag the next version so it can be tried by early adopters

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#68]
This should point to the next branch.
https://docs.npmjs.com/cli/dist-tag

**Comment by alexewerlof** [comment]
Seems like it could be automated with Travis [multi-deployment](https://docs.travis-ci.com/user/deployment) but since we have the `packages` directory it should be done manually. Not sure if Lerna (#44) can help.

Closing, unless a better solution exists.

One way forward would be to separate packages into their own repo (#69). Any other ideas that doesn't involve manual publishing from our own laptops?

**Comment by alexewerlof** [comment]
now that #69 is 👍 we can do this as well :)

**Comment by nosilleg** [comment]
This is an ongoing task when there are new versions. Closing this as done.
