### ISSUE TITLE
Separate the packages

### ISSUE THREAD

**Issue by alexewerlof** [schibsted/eslint-config-spt#69]
The monorepo is cool but #68 #46 show that at least the travis doesn't like them.
So I propose moving react config into its own repo because:

* Travis will be happy (in more formal language: we can use Travis deployment and `next` release for beta testers much simpler)
* The react config can be deployed and maintained independently from the js repo.
* The `package.json` in the root will be simpler to use because it points to an actual released package (#27 ). No more `cd packages/...` either.
* The react-specific issues can be grouped in their own repo. Different "expert groups" can decide not the rule set.
* We can close #44 (Lerna doesn't really seem to help with travis and #68 for example)

On the downside, we have to checkout two repos and we have to keep them in sync if there are any rule dependencies between the two (I can't see that happening too commonly though).

@SimenB I could really use an opinion here.

**Comment by SimenB** [comment]
I haven't looked too closely into this (as mentioned in DM, I've switched teams within Finn over the holidays, so time is spent familiarising myself with this new project), but I'd still like to see what comes of #44 before we make a decision here.

WRT auto deploy (#68?), we could then potentially use something like https://github.com/atlassian/lerna-semantic-release?

Off  hand though, I don't really see the need to automatically deploy from Travis, it's not that much work to deploy manually. I can see the advantage sure (if nothing else to reduce the human involvement), but I'm not sure multiple repos are an improvement on that.

**Comment by SimenB** [comment]
That said, if you're blocked on this, I vote 👍  for a split. Easy enough to merge back together later if the workflow improves.

Maybe wait for the other people involved? Not many people have actually involved themselves here, but @marek-nogiec and @dlmr has opened issues, so I'll tag them 😄

**Comment by alexewerlof** [comment]
Let's keep it open 2 more days if anyone has an objection. Pinging @ivarconr @nosilleg too.

**Comment by ivarconr** [comment]
we want to release these separately anyway. 

If it makes the process easier we should split (and as @SimenB we can always merge back). If we split then we also need to make sure to add a comment in the ready that links them together to make it easy for users to navigate.

**Comment by nosilleg** [comment]
My input...  It's not difficult or time consuming to release and tage to npm through cli.  That's what I had done with the previous versions including the beta.

My prefernece would be a less complicated dep tree at this stage.  As others have said, it's an easy revert, but I think the tendency is that revert don't happen that often in these situations.

All that being said, I'll defer to others and accept any decision made.

**Comment by nosilleg** [comment]
https://github.com/schibsted/eslint-config-schibsted/pull/75 makes use of Lerna instead of separating the packages.

Closing this as wont-fix.
