### ISSUE TITLE
Use/recommend prettier

### ISSUE THREAD

**Issue by SimenB** [schibsted/eslint-config-spt#70]
https://github.com/prettier/prettier

To always have fixable code, and guaranteed consistent styling, I propose to remove all styling rules (or at least remove them from standard config), and just recommend prettier.

If you haven't heard of prettier, it's basically standard (#47) or xo (#53) taken way further.

If it matters, some big projects are moving to it: facebook/react#9101, babel/babylon#390, facebook/jest#3057, facebook/immutable-js#1123

/cc @userpixel @sveisvei @ivarconr @nosilleg @dlmr @marek-nogiec @andreasrs

(I think I managed to tag everybody...)

**Comment by alexewerlof** [comment]
Good idea to separate styling rules to be prepared to adopt this.

**Comment by SimenB** [comment]
1.0 is released: http://jlongster.com/prettier-1.0

I'll throw together a preliminary PR after Easter

**Comment by nosilleg** [comment]
Addressed in https://github.com/schibsted/eslint-config-schibsted/pull/74
