### ISSUE TITLE
'no-unreachable':'error'

### ISSUE THREAD

**Issue by mtlewis** [schibsted/eslint-config-spt#71]
The [no-unreachable](http://eslint.org/docs/rules/no-unreachable) rule seems fairly uncontroversially to be a good rule to have turned on - can we consider adding this to eslint-config-schibsted?

```
function fn() {
    x = 1;
    return x;
    x = 3; // this will never execute
}
```

**Comment by SimenB** [comment]
Is that not active? Wow. +1 from me!

**Comment by nosilleg** [comment]
Addressed in https://github.com/schibsted/eslint-config-schibsted/pull/74

**Comment by nosilleg** [comment]
Closing as fixed in version 6.
