### ISSUE TITLE
Extract React rules into its own package

### ISSUE THREAD

**Issue by SimenB** [schibsted/eslint-config-spt#9]
It's currently a bit annoying to have to install `eslint-plugin-react` (or live with ugly warning from `npm>=3`) even for projects not using React.

Would it be possible to split up this package like airbnb (https://github.com/airbnb/javascript/tree/master/packages) has? One called `base` (or something), which is all current rules except react, and then the base one extends that, plus react rules (so remains the same as the current one).

I can make the code changes if you want

**Comment by ivarconr** [comment]
+1

**Comment by sveisvei** [comment]
+1

**Comment by nosilleg** [comment]
Sounds like a good change. A PR in the style of Airbnb would get my vote for merge.

**Comment by SimenB** [comment]
Merged into v3 🎉
